### ISSUE TITLE
Notification disappear

### ISSUE THREAD

**Issue by pfonda** [aneonex/BitcoinChecker#97]
The notification desappears all the time. :(

**Comment by aneonex** [comment]
Please describe the problem in more detail.

1. Which notifications you mean, price notifications or alarm notifications?
2. After which notifications disappear, some behavior symptoms?
3. What device you are using (model, android version)?
4. Any other details.

**Comment by pfonda** [comment]
The price notification only appears when I start the app. Then it
disappears.

I am using redmi note 7 android 10 miui 11
I don't know exactly when it disappears. But I will try to see if that
happens when another notification starts.
Tnx for your reply. Love this app

Peter Fonda
11 97141 4153

**Comment by aneonex** [comment]
Perhaps it will help:
1) Check that battery optimization is turned Off in the app settings
2) Check that app notifications are not disabled in Android settings. See section "Turn notifications on or off for certain apps" at https://support.google.com/android/answer/9079661

**Comment by pfonda** [comment]
I've just did some modifications. But the notification desappears.


Peter Fonda
11 97141 4153

**Comment by elino45** [comment]
Same problem of price update on specified time interval since the beginning, no modification made a change.
Manual refresh always works.
Isn't it possible to use the same code of manual price refreshing on  specified time to solve this issue which looks like many users are dealing with?

**Comment by aneonex** [comment]
@elino45 What device are you using?

I am guessing that some vendors (or device settings) block background tasks that run on a schedule.
User complaints about this problem are rare and no root cause has yet been found.

**Comment by elino45** [comment]
> @elino45 What device are you using?
> 
> I am guessing that some vendors (or device settings) block background tasks that run on a schedule.
> User complaints about this problem are rare and no root cause has yet been found.

Samsung galaxy a70
All other crypto and alert  apps I checked have no problem updating price. 
Tradingview. Coinalert . Binance app. Hitbtc app.... all working
Non have bitcoinchecker characteristics,
that's why I stiil wish this app works like old version.

**Comment by aneonex** [comment]
@elino45 @pfonda 
Try the new app version v2.30 (today published).
Updating the app caused the notification scheduler to stop, and as a result, notifications were no longer displayed. This has been fixed in the new version.

**Comment by pfonda** [comment]
Hooow awesooome!!! Tnx a lot guuuys! It looks like it is fixed now! Thank
you so much! This is the best app for tracking btc :)
I wish you guys the best!!!

Peter Fonda
11 97141 4153

**Comment by pfonda** [comment]
It still desappears actually :( sorry

Peter Fonda
11 97141 4153

**Comment by elino45** [comment]
Still the same, randomly price update. Recently updated to android 11, battery opt on, off... phone powersaving on, off... tried everything I could...no change ((

**Comment by aneonex** [comment]
Check please the latest app version 2.32. There have been several new improvements that could fix the problem.

**Comment by elino45** [comment]
> Check please the latest app version 2.32. There have been several new improvements that could fix the problem.

Finally managed to fix price update issue with latest update and power saving of device turned off even with battery optimization turned on! 
. No substitute for this app
Some other app for instance Binance app doesn't care about power saving or so . So maybe there's still some way that app works even in power saving mode.
Thank you anyway:)

**Comment by aneonex** [comment]
Great, thank you for update!
